version: "3.8"

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    # command: ./init.sh
    environment:
      NODE_ENV: production
      DOMAIN: "vocel.ru"
      MEDIASOUP_LISTEN_IP: "0.0.0.0"
      MEDIASOUP_ANNOUNCED_IP: "185.93.109.80"
    container_name: voicel-backend-production
    restart: always
    # volumes:
      # for development
      # - ./packages/backend:/usr/src/app
    ports:
      - 10000:10100
      - 44444:44444
      - 3000:3000
      - 8080
    networks:
      - nginx
  web-app:
    build:
      context: ./packages/web-app
      dockerfile: Dockerfile
    container_name: voicel-web-app-production
    restart: always
    ports:
      - 80
    networks:
      - nginx
    command: nginx -g "daemon off;"

networks:
  nginx:
    external: true