version: "3.8"

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    command: ./init.sh
    environment:
      NODE_ENV: production
    container_name: voicel-backend-production
    restart: always
    volumes:
      # for development
      - ./packages/backend:/usr/src/app
    ports:
      - "3000"
  web-app:
    build:
      context: ./packages/web-app
      dockerfile: Dockerfile
    container_name: voicel-web-app-production
    restart: always
    ports:
      - "80"
    command: nginx -g "daemon off;"
