version: "3.8"

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    container_name: voicel-backend-production
    restart: always
    volumes:
      # for development
      - ./packages/backend:/usr/src/app
    ports:
      - "3000"
