name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: Build and up docker containers
      run: docker-compose up --build -d
